In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use('ggplot')

In [13]:
csv = '../EBOV-Cyno-Aero-1.csv-Table 1.csv'

In [15]:
df = pd.read_csv(csv)
df

,Day,Time,TimeS,Study,SubjectName,AOPAMean_Mean,AOPAMean_Q25,AOPAMean_Q75,AOPDiastolic_Mean,AOPDiastolic_Q25,...,RR_Mean,RR_Q25,RR_Q75,RespMean_Mean,RespMean_Q25,RespMean_Q75,Temp_Mean,Temp_Q25,Temp_Q75,Y
0,0,16:32,1800,EBOV-Cyno-Aero-1,e1001,0.181102,-0.007103,0.495766,0.217047,0.020691,...,0.280620,-0.483330,1.220164,0.965805,0.471901,1.920801,0.004654,-0.086533,0.124863,0
1,0,17:02,3600,EBOV-Cyno-Aero-1,e1001,0.248157,0.178138,0.506787,0.249846,0.151380,...,1.090438,0.202607,1.731623,0.723821,0.757632,1.275255,-0.193890,-0.235937,-0.134840,0
2,0,17:32,5400,EBOV-Cyno-Aero-1,e1001,0.219259,0.208535,0.483133,0.258628,0.231031,...,0.632061,-0.326836,1.865233,0.352224,-0.213573,0.895737,0.003299,-0.122291,0.408073,0
3,0,18:02,7200,EBOV-Cyno-Aero-1,e1001,0.325888,0.160297,0.474509,0.332270,0.146847,...,0.859178,0.417893,1.338193,0.614939,-0.181273,1.728909,-0.563832,-1.597682,0.265006,0
4,0,18:32,9000,EBOV-Cyno-Aero-1,e1001,0.735482,0.664960,0.803540,0.701253,0.593551,...,0.884362,0.651263,1.158186,0.569164,-0.161620,1.218715,-0.008302,-0.269959,0.214836,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3765,6,7:28,1197000,EBOV-Cyno-Aero-1,e1015,-4.988405,-5.136460,-4.893404,-4.991035,-5.088935,...,-0.829866,-0.901046,-0.771905,1.509100,1.072225,1.747475,0.346893,0.216036,0.454264,1
3766,6,7:58,1198800,EBOV-Cyno-Aero-1,e1015,-5.322331,-5.584001,-5.099609,-5.488208,-5.703069,...,-0.892271,-0.921822,-0.857248,2.304838,1.690611,2.878129,-18.954136,-3.394366,-1.418412,1
3767,6,8:28,1200600,EBOV-Cyno-Aero-1,e1015,-6.625950,-6.840735,-6.463736,-6.641278,-6.845853,...,-0.736993,-0.765986,-0.693129,2.573127,2.276022,2.880280,-3.489655,-3.708318,-3.171848,1
3768,6,8:58,1202400,EBOV-Cyno-Aero-1,e1015,-7.449465,-7.912317,-6.982137,-7.525525,-7.965171,...,-0.942970,-0.978460,-0.909956,2.288502,1.814123,2.806958,-3.859444,-4.423121,-3.275484,1
3769,6,9:28,1204200,EBOV-Cyno-Aero-1,e1015,-7.673655,-7.804591,-7.562657,-7.740479,-7.872433,...,-0.779455,-0.760630,-0.610038,0.946044,0.275589,1.552854,-21.632378,-39.721619,-4.354561,1

In [35]:
df_table = pd.DataFrame(df.columns).set_index([0])
df_table.index.rename('Column', inplace=True)
df_table

Empty DataFrame
Columns: []
Index: [Day, Time, TimeS, Study, SubjectName, AOPAMean_Mean, AOPAMean_Q25, AOPAMean_Q75, AOPDiastolic_Mean, AOPDiastolic_Q25, AOPDiastolic_Q75, AOPSystolic_Mean, AOPSystolic_Q25, AOPSystolic_Q75, Activity_Mean, Activity_Q25, Activity_Q75, Bazett_Mean, Bazett_Q25, Bazett_Q75, Fridericia_Mean, Fridericia_Q25, Fridericia_Q75, HR_Mean, HR_Q25, HR_Q75, PR_Mean, PR_Q25, PR_Q75, QRS_Mean, QRS_Q25, QRS_Q75, QT_Mean, QT_Q25, QT_Q75, RR_Mean, RR_Q25, RR_Q75, RespMean_Mean, RespMean_Q25, RespMean_Q75, Temp_Mean, Temp_Q25, Temp_Q75, Y]